name: CI

on: [ push, pull_request ]

jobs:
    test:
        name: PHP ${{ matrix.php-version }}

        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - 8.4

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install PHP with extensions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    coverage: none

            -   name: Install dependencies
                run: composer install

            -   name: Run Coding Style Check
                run: php vendor/bin/php-cs-fixer check

            -   name: Run Rector
                run: php vendor/bin/rector --dry-run

#            -   name: Run Static Analysis
#                run: php vendor/bin/phpstan

            -   name: Run Tests
                run: php vendor/bin/phpunit
